[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "webhooksystems"
authors = [{name = "Maximilian", email = "ma@human-networks.com"}]
dynamic = ["version", "description"]
